sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t irwaank/udemy_docker -f Dockerfile.dev .

script:
  - docker run -e CI=true irwaank/udemy_docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  # The name of elasticbeanstalk
  app: "docker_udemy"
  env: "Dockerudemy-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-472653352833"
  # The "bucket_path" should exaclty same with value of "app"
  bucket_path: "docker_udemy"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"